# IEX Data Cleaner

Notebook này sẽ xử lý file `iex-data.xlsx` để đưa về dạng chuẩn: Agent | Activity | Start | End.
- Xử lý phần header dư thừa
- Chuẩn hóa tên cột
- Chuyển Start/End về datetime
- Xuất ra file sạch `iex_clean.csv`

In [20]:
import pandas as pd

# Hiển thị đủ số dòng và số cột mong muốn
pd.set_option("display.max_rows", 100)   # tối đa số dòng hiển thị
pd.set_option("display.max_columns", None)  # hiện tất cả các cột
pd.set_option("display.width", None)   # không giới hạn độ rộng

# Đọc file, bỏ 5 dòng đầu tiên
iex_df = pd.read_excel("iex-data.xlsx", skiprows=5)

# Bỏ những dòng toàn NaN
iex_df = iex_df.dropna(how="all")

# Xóa các cột toàn NaN
iex_df = iex_df.dropna(axis=1, how="all")

# Reset lại index
iex_df = iex_df.reset_index(drop=True)

# Xem thử 50 dòng đầu tiên
iex_df.head(50)

c:\Users\huuchinh.nguyen\AppData\Local\anaconda3\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

,MU: 1334 Expedia ENG Ho Chi Minh VNM,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 10
0,"Agent: 3052306 BUI, BADUONG",NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,Date,Start,End,Scheduled Activity,NaN,Start,End
2,NaN,8/18/25,Off,NaN,NaN,NaN,NaN,NaN
3,"Agent: 3085733 BUI, MINHAN",NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,Date,Start,End,Scheduled Activity,NaN,Start,End
5,NaN,8/18/25,Off,NaN,NaN,NaN,NaN,NaN
6,"Agent: 3092836 Bach, YenNhi",NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,Date,Start,End,Scheduled Activity,NaN,Start,End
8,NaN,8/18/25,6:00 AM,3:00 PM,NaN,Open Time,6:00 AM,6:45 AM
9,NaN,NaN,NaN,NaN,NaN,Break,6:45 AM,7:00 AM
10,NaN,NaN,NaN,NaN,NaN,Open Time,7:00 AM,12:00 PM
11,NaN,NaN,NaN,NaN,NaN,Lunch,12:00 PM,1:00 PM
12,NaN,NaN,NaN,NaN,NaN,Open Time,1:00 PM,1:45 PM
13,NaN,NaN,NaN,NaN,NaN,Break,1:45 PM,2:00 PM
14,NaN,NaN,NaN,NaN,NaN,Open Time,2:00 PM,3:00 PM
15,"Agent: 3097227 Bui, HoangCamNhung",NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,Date,Start,End,Scheduled Activity,NaN,Start,End
17,NaN,8/18/25,Off,NaN,NaN,NaN,NaN,NaN
18,"Agent: 3109394 Bui, NgocThuanVy",NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,Date,Start,End,Scheduled Activity,NaN,Start,End
20,NaN,8/18/25,10:00 PM,7:00 AM,NaN,Open Time,10:00 PM,11:45 PM
21,NaN,NaN,NaN,NaN,NaN,Break,11:45 PM,12:00 AM
22,NaN,NaN,NaN,NaN,NaN,Open Time,12:00 AM,1:40 AM
23,NaN,NaN,NaN,NaN,NaN,Lunch,1:40 AM,2:40 AM
24,NaN,NaN,NaN,NaN,NaN,Open Time,2:40 AM,5:00 AM
25,NaN,NaN,NaN,NaN,NaN,Break,5:00 AM,5:15 AM
26,NaN,NaN,NaN,NaN,NaN,Open Time,5:15 AM,7:00 AM
27,"Agent: 3109498 Bui, TheAnh",NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,NaN,Date,Start,End,Scheduled Activity,NaN,Start,End
29,NaN,8/18/25,8:00 PM,5:00 AM,NaN,Open Time,8:00 PM,9:15 PM
30,NaN,NaN,NaN,NaN,NaN,Break,9:15 PM,9:30 PM
31,NaN,NaN,NaN,NaN,NaN,Open Time,9:30 PM,10:30 PM
32,NaN,NaN,NaN,NaN,NaN,Lunch,10:30 PM,11:30 PM
33,NaN,NaN,NaN,NaN,NaN,Open Time,11:30 PM,1:45 AM
34,NaN,NaN,NaN,NaN,NaN,Break,1:45 AM,2:00 AM
35,NaN,NaN,NaN,NaN,NaN,Open Time,2:00 AM,5:00 AM
36,"Agent: 3093456 Bui, ThiNgocTram",NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,NaN,Date,Start,End,Scheduled Activity,NaN,Start,End
38,NaN,8/18/25,10:00 PM,7:00 AM,NaN,PTO,10:00 PM,2:20 AM
39,NaN,NaN,NaN,NaN,NaN,Lunch,2:20 AM,3:20 AM
40,"Agent: 3093456 Bui, ThiNgocTram",NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,NaN,Date,Start,End,Scheduled Activity,NaN,Start,End
42,NaN,NaN,NaN,NaN,NaN,PTO,3:20 AM,7:00 AM
43,"Agent: 3089245 Bui, TuongThinhNguyen",NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,NaN,Date,Start,End,Scheduled Activity,NaN,Start,End
45,NaN,8/18/25,Off,NaN,NaN,NaN,NaN,NaN
46,"Agent: 3091844 Cam, HoangKhang",NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,NaN,Date,Start,End,Scheduled Activity,NaN,Start,End
48,NaN,8/18/25,Off,NaN,NaN,NaN,NaN,NaN
49,"Agent: 3090882 Chau, HueHong",NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
# Gán lại tên cột thành số (0, 1, 2, ...)
iex_df.columns = range(iex_df.shape[1])

# Xem thử 20 dòng đầu
iex_df.head(20)

,0,1,2,3,4,5,6,7
0,"Agent: 3052306 BUI, BADUONG",NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,Date,Start,End,Scheduled Activity,NaN,Start,End
2,NaN,8/18/25,Off,NaN,NaN,NaN,NaN,NaN
3,"Agent: 3085733 BUI, MINHAN",NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,Date,Start,End,Scheduled Activity,NaN,Start,End
5,NaN,8/18/25,Off,NaN,NaN,NaN,NaN,NaN
6,"Agent: 3092836 Bach, YenNhi",NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,Date,Start,End,Scheduled Activity,NaN,Start,End
8,NaN,8/18/25,6:00 AM,3:00 PM,NaN,Open Time,6:00 AM,6:45 AM
9,NaN,NaN,NaN,NaN,NaN,Break,6:45 AM,7:00 AM
10,NaN,NaN,NaN,NaN,NaN,Open Time,7:00 AM,12:00 PM
11,NaN,NaN,NaN,NaN,NaN,Lunch,12:00 PM,1:00 PM
12,NaN,NaN,NaN,NaN,NaN,Open Time,1:00 PM,1:45 PM
13,NaN,NaN,NaN,NaN,NaN,Break,1:45 PM,2:00 PM
14,NaN,NaN,NaN,NaN,NaN,Open Time,2:00 PM,3:00 PM
15,"Agent: 3097227 Bui, HoangCamNhung",NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,Date,Start,End,Scheduled Activity,NaN,Start,End
17,NaN,8/18/25,Off,NaN,NaN,NaN,NaN,NaN
18,"Agent: 3109394 Bui, NgocThuanVy",NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,Date,Start,End,Scheduled Activity,NaN,Start,End

In [22]:
import re

# Hàm tách IEX Id và Name từ chuỗi
def split_agent_info(value):
    if isinstance(value, str) and value.startswith("Agent:"):
        # Loại bỏ "Agent:" rồi strip
        cleaned = value.replace("Agent:", "").strip()
        # Dùng regex tách id (số đầu tiên) và phần còn lại (tên)
        match = re.match(r"(\d+)\s+(.+)", cleaned)
        if match:
            return match.group(1), match.group(2)
    return None, None

# Tách thông tin Agent
iex_df["IEX Id"], iex_df["Name"] = zip(*iex_df[0].map(split_agent_info))

# Kiểm tra kết quả
iex_df.head(20)

,0,1,2,3,4,5,6,7,IEX Id,Name
0,"Agent: 3052306 BUI, BADUONG",NaN,NaN,NaN,NaN,NaN,NaN,NaN,3052306,"BUI, BADUONG"
1,NaN,Date,Start,End,Scheduled Activity,NaN,Start,End,None,None
2,NaN,8/18/25,Off,NaN,NaN,NaN,NaN,NaN,None,None
3,"Agent: 3085733 BUI, MINHAN",NaN,NaN,NaN,NaN,NaN,NaN,NaN,3085733,"BUI, MINHAN"
4,NaN,Date,Start,End,Scheduled Activity,NaN,Start,End,None,None
5,NaN,8/18/25,Off,NaN,NaN,NaN,NaN,NaN,None,None
6,"Agent: 3092836 Bach, YenNhi",NaN,NaN,NaN,NaN,NaN,NaN,NaN,3092836,"Bach, YenNhi"
7,NaN,Date,Start,End,Scheduled Activity,NaN,Start,End,None,None
8,NaN,8/18/25,6:00 AM,3:00 PM,NaN,Open Time,6:00 AM,6:45 AM,None,None
9,NaN,NaN,NaN,NaN,NaN,Break,6:45 AM,7:00 AM,None,None
10,NaN,NaN,NaN,NaN,NaN,Open Time,7:00 AM,12:00 PM,None,None
11,NaN,NaN,NaN,NaN,NaN,Lunch,12:00 PM,1:00 PM,None,None
12,NaN,NaN,NaN,NaN,NaN,Open Time,1:00 PM,1:45 PM,None,None
13,NaN,NaN,NaN,NaN,NaN,Break,1:45 PM,2:00 PM,None,None
14,NaN,NaN,NaN,NaN,NaN,Open Time,2:00 PM,3:00 PM,None,None
15,"Agent: 3097227 Bui, HoangCamNhung",NaN,NaN,NaN,NaN,NaN,NaN,NaN,3097227,"Bui, HoangCamNhung"
16,NaN,Date,Start,End,Scheduled Activity,NaN,Start,End,None,None
17,NaN,8/18/25,Off,NaN,NaN,NaN,NaN,NaN,None,None
18,"Agent: 3109394 Bui, NgocThuanVy",NaN,NaN,NaN,NaN,NaN,NaN,NaN,3109394,"Bui, NgocThuanVy"
19,NaN,Date,Start,End,Scheduled Activity,NaN,Start,End,None,None